### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by 8BallBomBom** [whisperity/SharpGMad#4] opened 2013-06-10 21:31 UTC
Every time i create a GMA file using your tool i get an exception with this error.

http://pastebin.com/nhEvs9Ja

If i click Continue then it gives me the update metadata box.
You don't seem to be able to change the author name.

If i set some information then click Accept, it will create the GMA file perfectly fine.
If i click Cancel then i get this exception.

http://pastebin.com/anWKiMgK

**Comment by whisperity** [comment] 2013-06-11 08:07
Thanks for the report, I will get down to look at it.
I knew about the first error happening and it should be fixed soon.

About the second one: thanks for pointing it out. Small overlooks. :smiley: They do happen.

> You don't seem to be able to change the author name.

This is as intended (at least for now) by garry. The original `gmad` code always writes only `Author Name` into the file. Until it is changed by him, I think SharpGMad should keep it the same for compatibility.

**Closed as completed** 2013-06-12 19:19 UTC
Labels: bug
